// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-backend.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, project_id, display_name, log_in_with_google, log_in_with_microsoft, log_in_with_email, log_in_with_password, log_in_with_saml, log_in_with_authenticator_app, log_in_with_passkey, scim_enabled)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

type CreateOrganizationParams struct {
	ID                        uuid.UUID
	ProjectID                 uuid.UUID
	DisplayName               string
	LogInWithGoogle           bool
	LogInWithMicrosoft        bool
	LogInWithEmail            bool
	LogInWithPassword         bool
	LogInWithSaml             bool
	LogInWithAuthenticatorApp bool
	LogInWithPasskey          bool
	ScimEnabled               bool
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.ProjectID,
		arg.DisplayName,
		arg.LogInWithGoogle,
		arg.LogInWithMicrosoft,
		arg.LogInWithEmail,
		arg.LogInWithPassword,
		arg.LogInWithSaml,
		arg.LogInWithAuthenticatorApp,
		arg.LogInWithPasskey,
		arg.ScimEnabled,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const createOrganizationGoogleHostedDomain = `-- name: CreateOrganizationGoogleHostedDomain :one
INSERT INTO organization_google_hosted_domains (id, organization_id, google_hosted_domain)
    VALUES ($1, $2, $3)
RETURNING
    id, organization_id, google_hosted_domain
`

type CreateOrganizationGoogleHostedDomainParams struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	GoogleHostedDomain string
}

func (q *Queries) CreateOrganizationGoogleHostedDomain(ctx context.Context, arg CreateOrganizationGoogleHostedDomainParams) (OrganizationGoogleHostedDomain, error) {
	row := q.db.QueryRow(ctx, createOrganizationGoogleHostedDomain, arg.ID, arg.OrganizationID, arg.GoogleHostedDomain)
	var i OrganizationGoogleHostedDomain
	err := row.Scan(&i.ID, &i.OrganizationID, &i.GoogleHostedDomain)
	return i, err
}

const createOrganizationMicrosoftTenantID = `-- name: CreateOrganizationMicrosoftTenantID :one
INSERT INTO organization_microsoft_tenant_ids (id, organization_id, microsoft_tenant_id)
    VALUES ($1, $2, $3)
RETURNING
    id, organization_id, microsoft_tenant_id
`

type CreateOrganizationMicrosoftTenantIDParams struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	MicrosoftTenantID string
}

func (q *Queries) CreateOrganizationMicrosoftTenantID(ctx context.Context, arg CreateOrganizationMicrosoftTenantIDParams) (OrganizationMicrosoftTenantID, error) {
	row := q.db.QueryRow(ctx, createOrganizationMicrosoftTenantID, arg.ID, arg.OrganizationID, arg.MicrosoftTenantID)
	var i OrganizationMicrosoftTenantID
	err := row.Scan(&i.ID, &i.OrganizationID, &i.MicrosoftTenantID)
	return i, err
}

const createProjectAPIKey = `-- name: CreateProjectAPIKey :one
INSERT INTO project_api_keys (id, project_id, display_name, secret_token_sha256)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, project_id, secret_token_sha256, display_name, create_time, update_time
`

type CreateProjectAPIKeyParams struct {
	ID                uuid.UUID
	ProjectID         uuid.UUID
	DisplayName       string
	SecretTokenSha256 []byte
}

func (q *Queries) CreateProjectAPIKey(ctx context.Context, arg CreateProjectAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, createProjectAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.DisplayName,
		arg.SecretTokenSha256,
	)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const createProjectTrustedDomain = `-- name: CreateProjectTrustedDomain :one
INSERT INTO project_trusted_domains (id, project_id, DOMAIN)
    VALUES ($1, $2, $3)
RETURNING
    id, project_id, domain
`

type CreateProjectTrustedDomainParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Domain    string
}

func (q *Queries) CreateProjectTrustedDomain(ctx context.Context, arg CreateProjectTrustedDomainParams) (ProjectTrustedDomain, error) {
	row := q.db.QueryRow(ctx, createProjectTrustedDomain, arg.ID, arg.ProjectID, arg.Domain)
	var i ProjectTrustedDomain
	err := row.Scan(&i.ID, &i.ProjectID, &i.Domain)
	return i, err
}

const createSAMLConnection = `-- name: CreateSAMLConnection :one
INSERT INTO saml_connections (id, organization_id, is_primary, idp_redirect_url, idp_x509_certificate, idp_entity_id)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, organization_id, create_time, is_primary, idp_redirect_url, idp_x509_certificate, idp_entity_id, update_time
`

type CreateSAMLConnectionParams struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	IsPrimary          bool
	IdpRedirectUrl     *string
	IdpX509Certificate []byte
	IdpEntityID        *string
}

func (q *Queries) CreateSAMLConnection(ctx context.Context, arg CreateSAMLConnectionParams) (SamlConnection, error) {
	row := q.db.QueryRow(ctx, createSAMLConnection,
		arg.ID,
		arg.OrganizationID,
		arg.IsPrimary,
		arg.IdpRedirectUrl,
		arg.IdpX509Certificate,
		arg.IdpEntityID,
	)
	var i SamlConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreateTime,
		&i.IsPrimary,
		&i.IdpRedirectUrl,
		&i.IdpX509Certificate,
		&i.IdpEntityID,
		&i.UpdateTime,
	)
	return i, err
}

const createSCIMAPIKey = `-- name: CreateSCIMAPIKey :one
INSERT INTO scim_api_keys (id, organization_id, display_name, secret_token_sha256)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, organization_id, secret_token_sha256, display_name, create_time, update_time
`

type CreateSCIMAPIKeyParams struct {
	ID                uuid.UUID
	OrganizationID    uuid.UUID
	DisplayName       string
	SecretTokenSha256 []byte
}

func (q *Queries) CreateSCIMAPIKey(ctx context.Context, arg CreateSCIMAPIKeyParams) (ScimApiKey, error) {
	row := q.db.QueryRow(ctx, createSCIMAPIKey,
		arg.ID,
		arg.OrganizationID,
		arg.DisplayName,
		arg.SecretTokenSha256,
	)
	var i ScimApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, organization_id, google_user_id, microsoft_user_id, email, is_owner)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, organization_id, password_bcrypt, google_user_id, microsoft_user_id, email, create_time, update_time, deactivate_time, is_owner, failed_password_attempts, password_lockout_expire_time, authenticator_app_secret_ciphertext, authenticator_app_recovery_code_bcrypts, failed_authenticator_app_attempts, authenticator_app_lockout_expire_time
`

type CreateUserParams struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	GoogleUserID    *string
	MicrosoftUserID *string
	Email           string
	IsOwner         bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.OrganizationID,
		arg.GoogleUserID,
		arg.MicrosoftUserID,
		arg.Email,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PasswordBcrypt,
		&i.GoogleUserID,
		&i.MicrosoftUserID,
		&i.Email,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeactivateTime,
		&i.IsOwner,
		&i.FailedPasswordAttempts,
		&i.PasswordLockoutExpireTime,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.FailedAuthenticatorAppAttempts,
		&i.AuthenticatorAppLockoutExpireTime,
	)
	return i, err
}

const createUserImpersonationToken = `-- name: CreateUserImpersonationToken :one
INSERT INTO user_impersonation_tokens (id, impersonator_id, impersonated_id, expire_time, secret_token_sha256)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, impersonator_id, create_time, expire_time, impersonated_id, secret_token_sha256
`

type CreateUserImpersonationTokenParams struct {
	ID                uuid.UUID
	ImpersonatorID    uuid.UUID
	ImpersonatedID    uuid.UUID
	ExpireTime        *time.Time
	SecretTokenSha256 []byte
}

func (q *Queries) CreateUserImpersonationToken(ctx context.Context, arg CreateUserImpersonationTokenParams) (UserImpersonationToken, error) {
	row := q.db.QueryRow(ctx, createUserImpersonationToken,
		arg.ID,
		arg.ImpersonatorID,
		arg.ImpersonatedID,
		arg.ExpireTime,
		arg.SecretTokenSha256,
	)
	var i UserImpersonationToken
	err := row.Scan(
		&i.ID,
		&i.ImpersonatorID,
		&i.CreateTime,
		&i.ExpireTime,
		&i.ImpersonatedID,
		&i.SecretTokenSha256,
	)
	return i, err
}

const createUserInvite = `-- name: CreateUserInvite :one
INSERT INTO user_invites (id, organization_id, email, is_owner)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id, email)
    DO UPDATE SET
        email = excluded.email, is_owner = excluded.is_owner
    RETURNING
        id, organization_id, create_time, update_time, email, is_owner
`

type CreateUserInviteParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Email          string
	IsOwner        bool
}

func (q *Queries) CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, createUserInvite,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.IsOwner,
	)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Email,
		&i.IsOwner,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const deleteOrganizationGoogleHostedDomains = `-- name: DeleteOrganizationGoogleHostedDomains :exec
DELETE FROM organization_google_hosted_domains
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationGoogleHostedDomains(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationGoogleHostedDomains, organizationID)
	return err
}

const deleteOrganizationMicrosoftTenantIDs = `-- name: DeleteOrganizationMicrosoftTenantIDs :exec
DELETE FROM organization_microsoft_tenant_ids
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationMicrosoftTenantIDs(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMicrosoftTenantIDs, organizationID)
	return err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM passkeys
WHERE id = $1
`

func (q *Queries) DeletePasskey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasskey, id)
	return err
}

const deleteProjectAPIKey = `-- name: DeleteProjectAPIKey :exec
DELETE FROM project_api_keys
WHERE id = $1
`

func (q *Queries) DeleteProjectAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectAPIKey, id)
	return err
}

const deleteProjectTrustedDomainsByProjectID = `-- name: DeleteProjectTrustedDomainsByProjectID :exec
DELETE FROM project_trusted_domains
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTrustedDomainsByProjectID(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTrustedDomainsByProjectID, projectID)
	return err
}

const deleteSAMLConnection = `-- name: DeleteSAMLConnection :exec
DELETE FROM saml_connections
WHERE id = $1
`

func (q *Queries) DeleteSAMLConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSAMLConnection, id)
	return err
}

const deleteSCIMAPIKey = `-- name: DeleteSCIMAPIKey :exec
DELETE FROM scim_api_keys
WHERE id = $1
`

func (q *Queries) DeleteSCIMAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSCIMAPIKey, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserInvite = `-- name: DeleteUserInvite :exec
DELETE FROM user_invites
WHERE id = $1
`

func (q *Queries) DeleteUserInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserInvite, id)
	return err
}

const disableOrganizationLogins = `-- name: DisableOrganizationLogins :exec
UPDATE
    organizations
SET
    logins_disabled = TRUE
WHERE
    id = $1
`

func (q *Queries) DisableOrganizationLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableOrganizationLogins, id)
	return err
}

const disableProjectLogins = `-- name: DisableProjectLogins :exec
UPDATE
    projects
SET
    logins_disabled = TRUE
WHERE
    id = $1
`

func (q *Queries) DisableProjectLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableProjectLogins, id)
	return err
}

const disableProjectOrganizationsLogInWithAuthenticatorApp = `-- name: DisableProjectOrganizationsLogInWithAuthenticatorApp :one
UPDATE
    organizations
SET
    log_in_with_authenticator_app = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithAuthenticatorApp(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithAuthenticatorApp, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithEmail = `-- name: DisableProjectOrganizationsLogInWithEmail :one
UPDATE
    organizations
SET
    log_in_with_email = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithEmail(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithEmail, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithGoogle = `-- name: DisableProjectOrganizationsLogInWithGoogle :one
UPDATE
    organizations
SET
    log_in_with_google = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithGoogle(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithGoogle, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithMicrosoft = `-- name: DisableProjectOrganizationsLogInWithMicrosoft :one
UPDATE
    organizations
SET
    log_in_with_microsoft = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithMicrosoft(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithMicrosoft, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithPasskey = `-- name: DisableProjectOrganizationsLogInWithPasskey :one
UPDATE
    organizations
SET
    log_in_with_passkey = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithPasskey(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithPasskey, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithPassword = `-- name: DisableProjectOrganizationsLogInWithPassword :one
UPDATE
    organizations
SET
    log_in_with_password = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithPassword(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithPassword, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const disableProjectOrganizationsLogInWithSAML = `-- name: DisableProjectOrganizationsLogInWithSAML :one
UPDATE
    organizations
SET
    log_in_with_saml = FALSE
WHERE
    project_id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

func (q *Queries) DisableProjectOrganizationsLogInWithSAML(ctx context.Context, projectID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, disableProjectOrganizationsLogInWithSAML, projectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const enableOrganizationLogins = `-- name: EnableOrganizationLogins :exec
UPDATE
    organizations
SET
    logins_disabled = FALSE
WHERE
    id = $1
`

func (q *Queries) EnableOrganizationLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableOrganizationLogins, id)
	return err
}

const enableProjectLogins = `-- name: EnableProjectLogins :exec
UPDATE
    projects
SET
    logins_disabled = FALSE
WHERE
    id = $1
`

func (q *Queries) EnableProjectLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableProjectLogins, id)
	return err
}

const existsUserWithEmailInOrganization = `-- name: ExistsUserWithEmailInOrganization :one
SELECT
    EXISTS (
        SELECT
            id, organization_id, password_bcrypt, google_user_id, microsoft_user_id, email, create_time, update_time, deactivate_time, is_owner, failed_password_attempts, password_lockout_expire_time, authenticator_app_secret_ciphertext, authenticator_app_recovery_code_bcrypts, failed_authenticator_app_attempts, authenticator_app_lockout_expire_time
        FROM
            users
        WHERE
            organization_id = $1
            AND email = $2)
`

type ExistsUserWithEmailInOrganizationParams struct {
	OrganizationID uuid.UUID
	Email          string
}

func (q *Queries) ExistsUserWithEmailInOrganization(ctx context.Context, arg ExistsUserWithEmailInOrganizationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserWithEmailInOrganization, arg.OrganizationID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIntermediateSession = `-- name: GetIntermediateSession :one
SELECT
    intermediate_sessions.id, intermediate_sessions.project_id, intermediate_sessions.create_time, intermediate_sessions.expire_time, intermediate_sessions.email, intermediate_sessions.google_oauth_state_sha256, intermediate_sessions.microsoft_oauth_state_sha256, intermediate_sessions.google_hosted_domain, intermediate_sessions.google_user_id, intermediate_sessions.microsoft_tenant_id, intermediate_sessions.microsoft_user_id, intermediate_sessions.password_verified, intermediate_sessions.organization_id, intermediate_sessions.update_time, intermediate_sessions.secret_token_sha256, intermediate_sessions.new_user_password_bcrypt, intermediate_sessions.email_verification_challenge_sha256, intermediate_sessions.email_verification_challenge_completed, intermediate_sessions.passkey_credential_id, intermediate_sessions.passkey_public_key, intermediate_sessions.passkey_aaguid, intermediate_sessions.passkey_verify_challenge_sha256, intermediate_sessions.passkey_verified, intermediate_sessions.authenticator_app_secret_ciphertext, intermediate_sessions.authenticator_app_verified, intermediate_sessions.authenticator_app_recovery_code_bcrypts, intermediate_sessions.primary_login_factor, intermediate_sessions.passkey_rp_id
FROM
    intermediate_sessions
WHERE
    id = $1
    AND project_id = $2
`

type GetIntermediateSessionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetIntermediateSession(ctx context.Context, arg GetIntermediateSessionParams) (IntermediateSession, error) {
	row := q.db.QueryRow(ctx, getIntermediateSession, arg.ID, arg.ProjectID)
	var i IntermediateSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreateTime,
		&i.ExpireTime,
		&i.Email,
		&i.GoogleOauthStateSha256,
		&i.MicrosoftOauthStateSha256,
		&i.GoogleHostedDomain,
		&i.GoogleUserID,
		&i.MicrosoftTenantID,
		&i.MicrosoftUserID,
		&i.PasswordVerified,
		&i.OrganizationID,
		&i.UpdateTime,
		&i.SecretTokenSha256,
		&i.NewUserPasswordBcrypt,
		&i.EmailVerificationChallengeSha256,
		&i.EmailVerificationChallengeCompleted,
		&i.PasskeyCredentialID,
		&i.PasskeyPublicKey,
		&i.PasskeyAaguid,
		&i.PasskeyVerifyChallengeSha256,
		&i.PasskeyVerified,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppVerified,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.PrimaryLoginFactor,
		&i.PasskeyRpID,
	)
	return i, err
}

const getOrganizationByProjectIDAndID = `-- name: GetOrganizationByProjectIDAndID :one
SELECT
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
FROM
    organizations
WHERE
    id = $1
    AND project_id = $2
`

type GetOrganizationByProjectIDAndIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetOrganizationByProjectIDAndID(ctx context.Context, arg GetOrganizationByProjectIDAndIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByProjectIDAndID, arg.ID, arg.ProjectID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const getOrganizationGoogleHostedDomains = `-- name: GetOrganizationGoogleHostedDomains :many
SELECT
    organization_google_hosted_domains.id, organization_google_hosted_domains.organization_id, organization_google_hosted_domains.google_hosted_domain
FROM
    organization_google_hosted_domains
    JOIN organizations ON organization_google_hosted_domains.organization_id = organizations.id
WHERE
    public.organization_google_hosted_domains.organization_id = $1
    AND organizations.project_id = $2
`

type GetOrganizationGoogleHostedDomainsParams struct {
	OrganizationID uuid.UUID
	ProjectID      uuid.UUID
}

func (q *Queries) GetOrganizationGoogleHostedDomains(ctx context.Context, arg GetOrganizationGoogleHostedDomainsParams) ([]OrganizationGoogleHostedDomain, error) {
	rows, err := q.db.Query(ctx, getOrganizationGoogleHostedDomains, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationGoogleHostedDomain
	for rows.Next() {
		var i OrganizationGoogleHostedDomain
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.GoogleHostedDomain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationMicrosoftTenantIDs = `-- name: GetOrganizationMicrosoftTenantIDs :many
SELECT
    organization_microsoft_tenant_ids.id, organization_microsoft_tenant_ids.organization_id, organization_microsoft_tenant_ids.microsoft_tenant_id
FROM
    organization_microsoft_tenant_ids
    JOIN organizations ON organization_microsoft_tenant_ids.organization_id = organizations.id
WHERE
    public.organization_microsoft_tenant_ids.organization_id = $1
    AND organizations.project_id = $2
`

type GetOrganizationMicrosoftTenantIDsParams struct {
	OrganizationID uuid.UUID
	ProjectID      uuid.UUID
}

func (q *Queries) GetOrganizationMicrosoftTenantIDs(ctx context.Context, arg GetOrganizationMicrosoftTenantIDsParams) ([]OrganizationMicrosoftTenantID, error) {
	rows, err := q.db.Query(ctx, getOrganizationMicrosoftTenantIDs, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationMicrosoftTenantID
	for rows.Next() {
		var i OrganizationMicrosoftTenantID
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.MicrosoftTenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasskey = `-- name: GetPasskey :one
SELECT
    passkeys.id, passkeys.user_id, passkeys.create_time, passkeys.update_time, passkeys.credential_id, passkeys.public_key, passkeys.aaguid, passkeys.disabled, passkeys.rp_id
FROM
    passkeys
    JOIN users ON passkeys.user_id = users.id
    JOIN organizations ON users.organization_id = organizations.id
WHERE
    passkeys.id = $1
    AND organizations.project_id = $2
`

type GetPasskeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetPasskey(ctx context.Context, arg GetPasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskey, arg.ID, arg.ProjectID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.Disabled,
		&i.RpID,
	)
	return i, err
}

const getProjectAPIKey = `-- name: GetProjectAPIKey :one
SELECT
    id, project_id, secret_token_sha256, display_name, create_time, update_time
FROM
    project_api_keys
WHERE
    id = $1
    AND project_id = $2
`

type GetProjectAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectAPIKey(ctx context.Context, arg GetProjectAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, getProjectAPIKey, arg.ID, arg.ProjectID)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getProjectAPIKeyBySecretTokenSHA256 = `-- name: GetProjectAPIKeyBySecretTokenSHA256 :one
SELECT
    id, project_id, secret_token_sha256, display_name, create_time, update_time
FROM
    project_api_keys
WHERE
    secret_token_sha256 = $1
`

func (q *Queries) GetProjectAPIKeyBySecretTokenSHA256(ctx context.Context, secretTokenSha256 []byte) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, getProjectAPIKeyBySecretTokenSHA256, secretTokenSha256)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT
    id, organization_id, log_in_with_password, log_in_with_google, log_in_with_microsoft, google_oauth_client_id, microsoft_oauth_client_id, google_oauth_client_secret_ciphertext, microsoft_oauth_client_secret_ciphertext, display_name, create_time, update_time, custom_auth_domain, auth_domain, logins_disabled, log_in_with_authenticator_app, log_in_with_passkey, log_in_with_email, log_in_with_saml, redirect_uri, after_login_redirect_uri, after_signup_redirect_uri
FROM
    projects
WHERE
    id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LogInWithPassword,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.GoogleOauthClientID,
		&i.MicrosoftOauthClientID,
		&i.GoogleOauthClientSecretCiphertext,
		&i.MicrosoftOauthClientSecretCiphertext,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
		&i.CustomAuthDomain,
		&i.AuthDomain,
		&i.LoginsDisabled,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
		&i.RedirectUri,
		&i.AfterLoginRedirectUri,
		&i.AfterSignupRedirectUri,
	)
	return i, err
}

const getProjectIDOrganizationBacks = `-- name: GetProjectIDOrganizationBacks :one
SELECT
    projects.id
FROM
    organizations
    JOIN projects ON projects.organization_id = organizations.id
WHERE
    organization_id = $1
`

func (q *Queries) GetProjectIDOrganizationBacks(ctx context.Context, organizationID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectIDOrganizationBacks, organizationID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectTrustedDomains = `-- name: GetProjectTrustedDomains :many
SELECT
    id, project_id, domain
FROM
    project_trusted_domains
WHERE
    project_id = $1
`

func (q *Queries) GetProjectTrustedDomains(ctx context.Context, projectID uuid.UUID) ([]ProjectTrustedDomain, error) {
	rows, err := q.db.Query(ctx, getProjectTrustedDomains, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectTrustedDomain
	for rows.Next() {
		var i ProjectTrustedDomain
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectUISettings = `-- name: GetProjectUISettings :one
SELECT
    id, project_id, primary_color, detect_dark_mode_enabled, dark_mode_primary_color, create_time, update_time, log_in_layout
FROM
    project_ui_settings
WHERE
    project_id = $1
`

func (q *Queries) GetProjectUISettings(ctx context.Context, projectID uuid.UUID) (ProjectUiSetting, error) {
	row := q.db.QueryRow(ctx, getProjectUISettings, projectID)
	var i ProjectUiSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PrimaryColor,
		&i.DetectDarkModeEnabled,
		&i.DarkModePrimaryColor,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LogInLayout,
	)
	return i, err
}

const getSAMLConnection = `-- name: GetSAMLConnection :one
SELECT
    saml_connections.id, saml_connections.organization_id, saml_connections.create_time, saml_connections.is_primary, saml_connections.idp_redirect_url, saml_connections.idp_x509_certificate, saml_connections.idp_entity_id, saml_connections.update_time
FROM
    saml_connections
    JOIN organizations ON saml_connections.organization_id = organizations.id
WHERE
    saml_connections.id = $1
    AND organizations.project_id = $2
`

type GetSAMLConnectionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSAMLConnection(ctx context.Context, arg GetSAMLConnectionParams) (SamlConnection, error) {
	row := q.db.QueryRow(ctx, getSAMLConnection, arg.ID, arg.ProjectID)
	var i SamlConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreateTime,
		&i.IsPrimary,
		&i.IdpRedirectUrl,
		&i.IdpX509Certificate,
		&i.IdpEntityID,
		&i.UpdateTime,
	)
	return i, err
}

const getSCIMAPIKey = `-- name: GetSCIMAPIKey :one
SELECT
    scim_api_keys.id, scim_api_keys.organization_id, scim_api_keys.secret_token_sha256, scim_api_keys.display_name, scim_api_keys.create_time, scim_api_keys.update_time
FROM
    scim_api_keys
    JOIN organizations ON scim_api_keys.organization_id = organizations.id
WHERE
    scim_api_keys.id = $1
    AND organizations.project_id = $2
`

type GetSCIMAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSCIMAPIKey(ctx context.Context, arg GetSCIMAPIKeyParams) (ScimApiKey, error) {
	row := q.db.QueryRow(ctx, getSCIMAPIKey, arg.ID, arg.ProjectID)
	var i ScimApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
    sessions.id, sessions.user_id, sessions.create_time, sessions.expire_time, sessions.refresh_token_sha256, sessions.impersonator_user_id, sessions.last_active_time
FROM
    sessions
    JOIN users ON sessions.user_id = users.id
    JOIN organizations ON users.organization_id = organizations.id
WHERE
    sessions.id = $1
    AND organizations.project_id = $2
`

type GetSessionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.ProjectID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreateTime,
		&i.ExpireTime,
		&i.RefreshTokenSha256,
		&i.ImpersonatorUserID,
		&i.LastActiveTime,
	)
	return i, err
}

const getSessionSigningKeysByProjectID = `-- name: GetSessionSigningKeysByProjectID :many
SELECT
    id, project_id, public_key, private_key_cipher_text, create_time, expire_time
FROM
    session_signing_keys
WHERE
    project_id = $1
`

func (q *Queries) GetSessionSigningKeysByProjectID(ctx context.Context, projectID uuid.UUID) ([]SessionSigningKey, error) {
	rows, err := q.db.Query(ctx, getSessionSigningKeysByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSigningKey
	for rows.Next() {
		var i SessionSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PublicKey,
			&i.PrivateKeyCipherText,
			&i.CreateTime,
			&i.ExpireTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT
    users.id, users.organization_id, users.password_bcrypt, users.google_user_id, users.microsoft_user_id, users.email, users.create_time, users.update_time, users.deactivate_time, users.is_owner, users.failed_password_attempts, users.password_lockout_expire_time, users.authenticator_app_secret_ciphertext, users.authenticator_app_recovery_code_bcrypts, users.failed_authenticator_app_attempts, users.authenticator_app_lockout_expire_time
FROM
    users
    JOIN organizations ON users.organization_id = organizations.id
WHERE
    users.id = $1
    AND organizations.project_id = $2
`

type GetUserParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.ProjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PasswordBcrypt,
		&i.GoogleUserID,
		&i.MicrosoftUserID,
		&i.Email,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeactivateTime,
		&i.IsOwner,
		&i.FailedPasswordAttempts,
		&i.PasswordLockoutExpireTime,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.FailedAuthenticatorAppAttempts,
		&i.AuthenticatorAppLockoutExpireTime,
	)
	return i, err
}

const getUserForImpersonation = `-- name: GetUserForImpersonation :one
SELECT
    users.id, users.organization_id, users.password_bcrypt, users.google_user_id, users.microsoft_user_id, users.email, users.create_time, users.update_time, users.deactivate_time, users.is_owner, users.failed_password_attempts, users.password_lockout_expire_time, users.authenticator_app_secret_ciphertext, users.authenticator_app_recovery_code_bcrypts, users.failed_authenticator_app_attempts, users.authenticator_app_lockout_expire_time
FROM
    users
    JOIN organizations ON users.organization_id = organizations.id
    JOIN projects ON organizations.id = projects.organization_id
WHERE
    users.id = $1
    AND projects.organization_id = $2
`

type GetUserForImpersonationParams struct {
	ID                         uuid.UUID
	ImpersonatorOrganizationID *uuid.UUID
}

func (q *Queries) GetUserForImpersonation(ctx context.Context, arg GetUserForImpersonationParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserForImpersonation, arg.ID, arg.ImpersonatorOrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PasswordBcrypt,
		&i.GoogleUserID,
		&i.MicrosoftUserID,
		&i.Email,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeactivateTime,
		&i.IsOwner,
		&i.FailedPasswordAttempts,
		&i.PasswordLockoutExpireTime,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.FailedAuthenticatorAppAttempts,
		&i.AuthenticatorAppLockoutExpireTime,
	)
	return i, err
}

const getUserInvite = `-- name: GetUserInvite :one
SELECT
    user_invites.id, user_invites.organization_id, user_invites.create_time, user_invites.update_time, user_invites.email, user_invites.is_owner
FROM
    user_invites
    JOIN organizations ON user_invites.organization_id = organizations.id
WHERE
    user_invites.id = $1
    AND organizations.project_id = $2
`

type GetUserInviteParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetUserInvite(ctx context.Context, arg GetUserInviteParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, getUserInvite, arg.ID, arg.ProjectID)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Email,
		&i.IsOwner,
	)
	return i, err
}

const listIntermediateSessions = `-- name: ListIntermediateSessions :many
SELECT
    id, project_id, create_time, expire_time, email, google_oauth_state_sha256, microsoft_oauth_state_sha256, google_hosted_domain, google_user_id, microsoft_tenant_id, microsoft_user_id, password_verified, organization_id, update_time, secret_token_sha256, new_user_password_bcrypt, email_verification_challenge_sha256, email_verification_challenge_completed, passkey_credential_id, passkey_public_key, passkey_aaguid, passkey_verify_challenge_sha256, passkey_verified, authenticator_app_secret_ciphertext, authenticator_app_verified, authenticator_app_recovery_code_bcrypts, primary_login_factor, passkey_rp_id
FROM
    intermediate_sessions
WHERE
    project_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListIntermediateSessionsParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
	Limit     int32
}

func (q *Queries) ListIntermediateSessions(ctx context.Context, arg ListIntermediateSessionsParams) ([]IntermediateSession, error) {
	rows, err := q.db.Query(ctx, listIntermediateSessions, arg.ProjectID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntermediateSession
	for rows.Next() {
		var i IntermediateSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreateTime,
			&i.ExpireTime,
			&i.Email,
			&i.GoogleOauthStateSha256,
			&i.MicrosoftOauthStateSha256,
			&i.GoogleHostedDomain,
			&i.GoogleUserID,
			&i.MicrosoftTenantID,
			&i.MicrosoftUserID,
			&i.PasswordVerified,
			&i.OrganizationID,
			&i.UpdateTime,
			&i.SecretTokenSha256,
			&i.NewUserPasswordBcrypt,
			&i.EmailVerificationChallengeSha256,
			&i.EmailVerificationChallengeCompleted,
			&i.PasskeyCredentialID,
			&i.PasskeyPublicKey,
			&i.PasskeyAaguid,
			&i.PasskeyVerifyChallengeSha256,
			&i.PasskeyVerified,
			&i.AuthenticatorAppSecretCiphertext,
			&i.AuthenticatorAppVerified,
			&i.AuthenticatorAppRecoveryCodeBcrypts,
			&i.PrimaryLoginFactor,
			&i.PasskeyRpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByProjectId = `-- name: ListOrganizationsByProjectId :many
SELECT
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
FROM
    organizations
WHERE
    project_id = $1
ORDER BY
    id
LIMIT $2
`

type ListOrganizationsByProjectIdParams struct {
	ProjectID uuid.UUID
	Limit     int32
}

func (q *Queries) ListOrganizationsByProjectId(ctx context.Context, arg ListOrganizationsByProjectIdParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByProjectId, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DisplayName,
			&i.ScimEnabled,
			&i.CreateTime,
			&i.UpdateTime,
			&i.LoginsDisabled,
			&i.LogInWithGoogle,
			&i.LogInWithMicrosoft,
			&i.LogInWithPassword,
			&i.LogInWithAuthenticatorApp,
			&i.LogInWithPasskey,
			&i.RequireMfa,
			&i.LogInWithEmail,
			&i.LogInWithSaml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT
    id, user_id, create_time, update_time, credential_id, public_key, aaguid, disabled, rp_id
FROM
    passkeys
WHERE
    user_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListPasskeysParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Limit  int32
}

func (q *Queries) ListPasskeys(ctx context.Context, arg ListPasskeysParams) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeys, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreateTime,
			&i.UpdateTime,
			&i.CredentialID,
			&i.PublicKey,
			&i.Aaguid,
			&i.Disabled,
			&i.RpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectAPIKeys = `-- name: ListProjectAPIKeys :many
SELECT
    id, project_id, secret_token_sha256, display_name, create_time, update_time
FROM
    project_api_keys
WHERE
    project_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListProjectAPIKeysParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
	Limit     int32
}

func (q *Queries) ListProjectAPIKeys(ctx context.Context, arg ListProjectAPIKeysParams) ([]ProjectApiKey, error) {
	rows, err := q.db.Query(ctx, listProjectAPIKeys, arg.ProjectID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectApiKey
	for rows.Next() {
		var i ProjectApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SecretTokenSha256,
			&i.DisplayName,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT
    id, organization_id, log_in_with_password, log_in_with_google, log_in_with_microsoft, google_oauth_client_id, microsoft_oauth_client_id, google_oauth_client_secret_ciphertext, microsoft_oauth_client_secret_ciphertext, display_name, create_time, update_time, custom_auth_domain, auth_domain, logins_disabled, log_in_with_authenticator_app, log_in_with_passkey, log_in_with_email, log_in_with_saml, redirect_uri, after_login_redirect_uri, after_signup_redirect_uri
FROM
    projects
ORDER BY
    id
LIMIT $1
`

func (q *Queries) ListProjects(ctx context.Context, limit int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.LogInWithPassword,
			&i.LogInWithGoogle,
			&i.LogInWithMicrosoft,
			&i.GoogleOauthClientID,
			&i.MicrosoftOauthClientID,
			&i.GoogleOauthClientSecretCiphertext,
			&i.MicrosoftOauthClientSecretCiphertext,
			&i.DisplayName,
			&i.CreateTime,
			&i.UpdateTime,
			&i.CustomAuthDomain,
			&i.AuthDomain,
			&i.LoginsDisabled,
			&i.LogInWithAuthenticatorApp,
			&i.LogInWithPasskey,
			&i.LogInWithEmail,
			&i.LogInWithSaml,
			&i.RedirectUri,
			&i.AfterLoginRedirectUri,
			&i.AfterSignupRedirectUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLConnections = `-- name: ListSAMLConnections :many
SELECT
    id, organization_id, create_time, is_primary, idp_redirect_url, idp_x509_certificate, idp_entity_id, update_time
FROM
    saml_connections
WHERE
    organization_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListSAMLConnectionsParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

func (q *Queries) ListSAMLConnections(ctx context.Context, arg ListSAMLConnectionsParams) ([]SamlConnection, error) {
	rows, err := q.db.Query(ctx, listSAMLConnections, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlConnection
	for rows.Next() {
		var i SamlConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreateTime,
			&i.IsPrimary,
			&i.IdpRedirectUrl,
			&i.IdpX509Certificate,
			&i.IdpEntityID,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMAPIKeys = `-- name: ListSCIMAPIKeys :many
SELECT
    id, organization_id, secret_token_sha256, display_name, create_time, update_time
FROM
    scim_api_keys
WHERE
    organization_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListSCIMAPIKeysParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

func (q *Queries) ListSCIMAPIKeys(ctx context.Context, arg ListSCIMAPIKeysParams) ([]ScimApiKey, error) {
	rows, err := q.db.Query(ctx, listSCIMAPIKeys, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimApiKey
	for rows.Next() {
		var i ScimApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SecretTokenSha256,
			&i.DisplayName,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT
    id, user_id, create_time, expire_time, refresh_token_sha256, impersonator_user_id, last_active_time
FROM
    sessions
WHERE
    user_id = $1
    AND id <= $2
ORDER BY
    id DESC
LIMIT $3
`

type ListSessionsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Limit  int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreateTime,
			&i.ExpireTime,
			&i.RefreshTokenSha256,
			&i.ImpersonatorUserID,
			&i.LastActiveTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInvites = `-- name: ListUserInvites :many
SELECT
    id, organization_id, create_time, update_time, email, is_owner
FROM
    user_invites
WHERE
    organization_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListUserInvitesParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

func (q *Queries) ListUserInvites(ctx context.Context, arg ListUserInvitesParams) ([]UserInvite, error) {
	rows, err := q.db.Query(ctx, listUserInvites, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInvite
	for rows.Next() {
		var i UserInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Email,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, organization_id, password_bcrypt, google_user_id, microsoft_user_id, email, create_time, update_time, deactivate_time, is_owner, failed_password_attempts, password_lockout_expire_time, authenticator_app_secret_ciphertext, authenticator_app_recovery_code_bcrypts, failed_authenticator_app_attempts, authenticator_app_lockout_expire_time
FROM
    users
WHERE
    organization_id = $1
    AND id >= $2
ORDER BY
    id
LIMIT $3
`

type ListUsersParams struct {
	OrganizationID uuid.UUID
	ID             uuid.UUID
	Limit          int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PasswordBcrypt,
			&i.GoogleUserID,
			&i.MicrosoftUserID,
			&i.Email,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DeactivateTime,
			&i.IsOwner,
			&i.FailedPasswordAttempts,
			&i.PasswordLockoutExpireTime,
			&i.AuthenticatorAppSecretCiphertext,
			&i.AuthenticatorAppRecoveryCodeBcrypts,
			&i.FailedAuthenticatorAppAttempts,
			&i.AuthenticatorAppLockoutExpireTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOrganizationSessions = `-- name: RevokeAllOrganizationSessions :exec
UPDATE
    sessions
SET
    refresh_token_sha256 = NULL
WHERE
    user_id IN (
        SELECT
            id
        FROM
            users
        WHERE
            organization_id = $1)
`

func (q *Queries) RevokeAllOrganizationSessions(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllOrganizationSessions, organizationID)
	return err
}

const revokeAllProjectSessions = `-- name: RevokeAllProjectSessions :exec
UPDATE
    sessions
SET
    refresh_token_sha256 = NULL
WHERE
    user_id IN (
        SELECT
            id
        FROM
            users
        WHERE
            organization_id IN (
                SELECT
                    id
                FROM
                    organizations
                WHERE
                    project_id = $1))
`

func (q *Queries) RevokeAllProjectSessions(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllProjectSessions, projectID)
	return err
}

const revokeProjectAPIKey = `-- name: RevokeProjectAPIKey :one
UPDATE
    project_api_keys
SET
    update_time = now(),
    secret_token_sha256 = NULL
WHERE
    id = $1
RETURNING
    id, project_id, secret_token_sha256, display_name, create_time, update_time
`

func (q *Queries) RevokeProjectAPIKey(ctx context.Context, id uuid.UUID) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, revokeProjectAPIKey, id)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const revokeSCIMAPIKey = `-- name: RevokeSCIMAPIKey :one
UPDATE
    scim_api_keys
SET
    update_time = now(),
    secret_token_sha256 = NULL
WHERE
    id = $1
RETURNING
    id, organization_id, secret_token_sha256, display_name, create_time, update_time
`

func (q *Queries) RevokeSCIMAPIKey(ctx context.Context, id uuid.UUID) (ScimApiKey, error) {
	row := q.db.QueryRow(ctx, revokeSCIMAPIKey, id)
	var i ScimApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE
    organizations
SET
    update_time = now(),
    display_name = $2,
    log_in_with_google = $3,
    log_in_with_microsoft = $4,
    log_in_with_email = $5,
    log_in_with_password = $6,
    log_in_with_authenticator_app = $7,
    log_in_with_passkey = $8,
    log_in_with_saml = $9,
    scim_enabled = $10
WHERE
    id = $1
RETURNING
    id, project_id, display_name, scim_enabled, create_time, update_time, logins_disabled, log_in_with_google, log_in_with_microsoft, log_in_with_password, log_in_with_authenticator_app, log_in_with_passkey, require_mfa, log_in_with_email, log_in_with_saml
`

type UpdateOrganizationParams struct {
	ID                        uuid.UUID
	DisplayName               string
	LogInWithGoogle           bool
	LogInWithMicrosoft        bool
	LogInWithEmail            bool
	LogInWithPassword         bool
	LogInWithAuthenticatorApp bool
	LogInWithPasskey          bool
	LogInWithSaml             bool
	ScimEnabled               bool
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.DisplayName,
		arg.LogInWithGoogle,
		arg.LogInWithMicrosoft,
		arg.LogInWithEmail,
		arg.LogInWithPassword,
		arg.LogInWithAuthenticatorApp,
		arg.LogInWithPasskey,
		arg.LogInWithSaml,
		arg.ScimEnabled,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DisplayName,
		&i.ScimEnabled,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LoginsDisabled,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.LogInWithPassword,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.RequireMfa,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
	)
	return i, err
}

const updatePasskey = `-- name: UpdatePasskey :one
UPDATE
    passkeys
SET
    update_time = now(),
    disabled = $2
WHERE
    id = $1
RETURNING
    id, user_id, create_time, update_time, credential_id, public_key, aaguid, disabled, rp_id
`

type UpdatePasskeyParams struct {
	ID       uuid.UUID
	Disabled bool
}

func (q *Queries) UpdatePasskey(ctx context.Context, arg UpdatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, updatePasskey, arg.ID, arg.Disabled)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.Disabled,
		&i.RpID,
	)
	return i, err
}

const updatePrimarySAMLConnection = `-- name: UpdatePrimarySAMLConnection :exec
UPDATE
    saml_connections
SET
    is_primary = (id = $1)
WHERE
    organization_id = $2
`

type UpdatePrimarySAMLConnectionParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) UpdatePrimarySAMLConnection(ctx context.Context, arg UpdatePrimarySAMLConnectionParams) error {
	_, err := q.db.Exec(ctx, updatePrimarySAMLConnection, arg.ID, arg.OrganizationID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE
    projects
SET
    update_time = now(),
    display_name = $2,
    log_in_with_google = $3,
    log_in_with_microsoft = $4,
    log_in_with_email = $5,
    log_in_with_password = $6,
    log_in_with_saml = $7,
    log_in_with_authenticator_app = $8,
    log_in_with_passkey = $9,
    google_oauth_client_id = $10,
    google_oauth_client_secret_ciphertext = $11,
    microsoft_oauth_client_id = $12,
    microsoft_oauth_client_secret_ciphertext = $13,
    custom_auth_domain = $14,
    auth_domain = $15,
    redirect_uri = $16,
    after_login_redirect_uri = $17,
    after_signup_redirect_uri = $18
WHERE
    id = $1
RETURNING
    id, organization_id, log_in_with_password, log_in_with_google, log_in_with_microsoft, google_oauth_client_id, microsoft_oauth_client_id, google_oauth_client_secret_ciphertext, microsoft_oauth_client_secret_ciphertext, display_name, create_time, update_time, custom_auth_domain, auth_domain, logins_disabled, log_in_with_authenticator_app, log_in_with_passkey, log_in_with_email, log_in_with_saml, redirect_uri, after_login_redirect_uri, after_signup_redirect_uri
`

type UpdateProjectParams struct {
	ID                                   uuid.UUID
	DisplayName                          string
	LogInWithGoogle                      bool
	LogInWithMicrosoft                   bool
	LogInWithEmail                       bool
	LogInWithPassword                    bool
	LogInWithSaml                        bool
	LogInWithAuthenticatorApp            bool
	LogInWithPasskey                     bool
	GoogleOauthClientID                  *string
	GoogleOauthClientSecretCiphertext    []byte
	MicrosoftOauthClientID               *string
	MicrosoftOauthClientSecretCiphertext []byte
	CustomAuthDomain                     *string
	AuthDomain                           *string
	RedirectUri                          *string
	AfterLoginRedirectUri                *string
	AfterSignupRedirectUri               *string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.DisplayName,
		arg.LogInWithGoogle,
		arg.LogInWithMicrosoft,
		arg.LogInWithEmail,
		arg.LogInWithPassword,
		arg.LogInWithSaml,
		arg.LogInWithAuthenticatorApp,
		arg.LogInWithPasskey,
		arg.GoogleOauthClientID,
		arg.GoogleOauthClientSecretCiphertext,
		arg.MicrosoftOauthClientID,
		arg.MicrosoftOauthClientSecretCiphertext,
		arg.CustomAuthDomain,
		arg.AuthDomain,
		arg.RedirectUri,
		arg.AfterLoginRedirectUri,
		arg.AfterSignupRedirectUri,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LogInWithPassword,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.GoogleOauthClientID,
		&i.MicrosoftOauthClientID,
		&i.GoogleOauthClientSecretCiphertext,
		&i.MicrosoftOauthClientSecretCiphertext,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
		&i.CustomAuthDomain,
		&i.AuthDomain,
		&i.LoginsDisabled,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
		&i.RedirectUri,
		&i.AfterLoginRedirectUri,
		&i.AfterSignupRedirectUri,
	)
	return i, err
}

const updateProjectAPIKey = `-- name: UpdateProjectAPIKey :one
UPDATE
    project_api_keys
SET
    update_time = now(),
    display_name = $1
WHERE
    id = $2
RETURNING
    id, project_id, secret_token_sha256, display_name, create_time, update_time
`

type UpdateProjectAPIKeyParams struct {
	DisplayName string
	ID          uuid.UUID
}

func (q *Queries) UpdateProjectAPIKey(ctx context.Context, arg UpdateProjectAPIKeyParams) (ProjectApiKey, error) {
	row := q.db.QueryRow(ctx, updateProjectAPIKey, arg.DisplayName, arg.ID)
	var i ProjectApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateProjectOrganizationID = `-- name: UpdateProjectOrganizationID :one
UPDATE
    projects
SET
    organization_id = $2
WHERE
    id = $1
RETURNING
    id, organization_id, log_in_with_password, log_in_with_google, log_in_with_microsoft, google_oauth_client_id, microsoft_oauth_client_id, google_oauth_client_secret_ciphertext, microsoft_oauth_client_secret_ciphertext, display_name, create_time, update_time, custom_auth_domain, auth_domain, logins_disabled, log_in_with_authenticator_app, log_in_with_passkey, log_in_with_email, log_in_with_saml, redirect_uri, after_login_redirect_uri, after_signup_redirect_uri
`

type UpdateProjectOrganizationIDParams struct {
	ID             uuid.UUID
	OrganizationID *uuid.UUID
}

func (q *Queries) UpdateProjectOrganizationID(ctx context.Context, arg UpdateProjectOrganizationIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectOrganizationID, arg.ID, arg.OrganizationID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LogInWithPassword,
		&i.LogInWithGoogle,
		&i.LogInWithMicrosoft,
		&i.GoogleOauthClientID,
		&i.MicrosoftOauthClientID,
		&i.GoogleOauthClientSecretCiphertext,
		&i.MicrosoftOauthClientSecretCiphertext,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
		&i.CustomAuthDomain,
		&i.AuthDomain,
		&i.LoginsDisabled,
		&i.LogInWithAuthenticatorApp,
		&i.LogInWithPasskey,
		&i.LogInWithEmail,
		&i.LogInWithSaml,
		&i.RedirectUri,
		&i.AfterLoginRedirectUri,
		&i.AfterSignupRedirectUri,
	)
	return i, err
}

const updateProjectUISettings = `-- name: UpdateProjectUISettings :one
UPDATE
    project_ui_settings
SET
    update_time = now(),
    primary_color = $3,
    detect_dark_mode_enabled = $4,
    dark_mode_primary_color = $5
WHERE
    id = $1
    AND project_id = $2
RETURNING
    id, project_id, primary_color, detect_dark_mode_enabled, dark_mode_primary_color, create_time, update_time, log_in_layout
`

type UpdateProjectUISettingsParams struct {
	ID                    uuid.UUID
	ProjectID             uuid.UUID
	PrimaryColor          *string
	DetectDarkModeEnabled bool
	DarkModePrimaryColor  *string
}

func (q *Queries) UpdateProjectUISettings(ctx context.Context, arg UpdateProjectUISettingsParams) (ProjectUiSetting, error) {
	row := q.db.QueryRow(ctx, updateProjectUISettings,
		arg.ID,
		arg.ProjectID,
		arg.PrimaryColor,
		arg.DetectDarkModeEnabled,
		arg.DarkModePrimaryColor,
	)
	var i ProjectUiSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PrimaryColor,
		&i.DetectDarkModeEnabled,
		&i.DarkModePrimaryColor,
		&i.CreateTime,
		&i.UpdateTime,
		&i.LogInLayout,
	)
	return i, err
}

const updateSAMLConnection = `-- name: UpdateSAMLConnection :one
UPDATE
    saml_connections
SET
    update_time = now(),
    is_primary = $1,
    idp_redirect_url = $2,
    idp_x509_certificate = $3,
    idp_entity_id = $4
WHERE
    id = $5
RETURNING
    id, organization_id, create_time, is_primary, idp_redirect_url, idp_x509_certificate, idp_entity_id, update_time
`

type UpdateSAMLConnectionParams struct {
	IsPrimary          bool
	IdpRedirectUrl     *string
	IdpX509Certificate []byte
	IdpEntityID        *string
	ID                 uuid.UUID
}

func (q *Queries) UpdateSAMLConnection(ctx context.Context, arg UpdateSAMLConnectionParams) (SamlConnection, error) {
	row := q.db.QueryRow(ctx, updateSAMLConnection,
		arg.IsPrimary,
		arg.IdpRedirectUrl,
		arg.IdpX509Certificate,
		arg.IdpEntityID,
		arg.ID,
	)
	var i SamlConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreateTime,
		&i.IsPrimary,
		&i.IdpRedirectUrl,
		&i.IdpX509Certificate,
		&i.IdpEntityID,
		&i.UpdateTime,
	)
	return i, err
}

const updateSCIMAPIKey = `-- name: UpdateSCIMAPIKey :one
UPDATE
    scim_api_keys
SET
    update_time = now(),
    display_name = $1
WHERE
    id = $2
RETURNING
    id, organization_id, secret_token_sha256, display_name, create_time, update_time
`

type UpdateSCIMAPIKeyParams struct {
	DisplayName string
	ID          uuid.UUID
}

func (q *Queries) UpdateSCIMAPIKey(ctx context.Context, arg UpdateSCIMAPIKeyParams) (ScimApiKey, error) {
	row := q.db.QueryRow(ctx, updateSCIMAPIKey, arg.DisplayName, arg.ID)
	var i ScimApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SecretTokenSha256,
		&i.DisplayName,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    update_time = now(),
    email = $2,
    google_user_id = $3,
    microsoft_user_id = $4,
    is_owner = $5
WHERE
    id = $1
RETURNING
    id, organization_id, password_bcrypt, google_user_id, microsoft_user_id, email, create_time, update_time, deactivate_time, is_owner, failed_password_attempts, password_lockout_expire_time, authenticator_app_secret_ciphertext, authenticator_app_recovery_code_bcrypts, failed_authenticator_app_attempts, authenticator_app_lockout_expire_time
`

type UpdateUserParams struct {
	ID              uuid.UUID
	Email           string
	GoogleUserID    *string
	MicrosoftUserID *string
	IsOwner         bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.GoogleUserID,
		arg.MicrosoftUserID,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PasswordBcrypt,
		&i.GoogleUserID,
		&i.MicrosoftUserID,
		&i.Email,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeactivateTime,
		&i.IsOwner,
		&i.FailedPasswordAttempts,
		&i.PasswordLockoutExpireTime,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.FailedAuthenticatorAppAttempts,
		&i.AuthenticatorAppLockoutExpireTime,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE
    users
SET
    update_time = now(),
    password_bcrypt = $2
WHERE
    id = $1
RETURNING
    id, organization_id, password_bcrypt, google_user_id, microsoft_user_id, email, create_time, update_time, deactivate_time, is_owner, failed_password_attempts, password_lockout_expire_time, authenticator_app_secret_ciphertext, authenticator_app_recovery_code_bcrypts, failed_authenticator_app_attempts, authenticator_app_lockout_expire_time
`

type UpdateUserPasswordParams struct {
	ID             uuid.UUID
	PasswordBcrypt *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordBcrypt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PasswordBcrypt,
		&i.GoogleUserID,
		&i.MicrosoftUserID,
		&i.Email,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DeactivateTime,
		&i.IsOwner,
		&i.FailedPasswordAttempts,
		&i.PasswordLockoutExpireTime,
		&i.AuthenticatorAppSecretCiphertext,
		&i.AuthenticatorAppRecoveryCodeBcrypts,
		&i.FailedAuthenticatorAppAttempts,
		&i.AuthenticatorAppLockoutExpireTime,
	)
	return i, err
}
