services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_PASSWORD: "password"
    network_mode: host
    ports:
      - 5432
  app:
    build: ./app
    ports:
      - 8080
    volumes:
      - ./app:/app
    command: ["npm", "run", "dev"]
  api:
    image: golang:1.23-alpine
    expose:
      - 8081
    network_mode: host
    ports:
      - 8081
    depends_on:
      - postgres
    volumes:
      - .:/api
    working_dir: /api
    command: ["go", "run", "./cmd/api"]
  ui:
    build: ./ui
    ports:
      - 8082
    volumes:
      - ./ui:/ui
    command: ["npm", "run", "dev"]
