services:
  app:
    build: ./app
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  api:
    command: ["go", "run", "./cmd/api"]
    environment:
      API_DB: "postgres://postgres:password@postgres:5432/postgres"
    image: golang:1.23-alpine
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - .:/api
    working_dir: /api
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_PASSWORD: "password"
    expose:
      - 5432
    ports:
      - "5432:5432"
  ui:
    build: ./ui
    command: ["npm", "run", "dev"]
    ports:
      - "8082:8082"
    volumes:
      - ./ui:/ui
