apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
spec:
  scheme: internet-facing
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  annotations:
    # Use this annotation to set an IngressClass as Default
    # If an Ingress doesn't specify a class, it will use the Default
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  # Configures the IngressClass to use EKS Auto Mode
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: alb
---
apiVersion: v1
kind: Namespace
metadata:
  name: tesseral
  labels:
    name: tesseral
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tesseral
  name: tesseral-internal-api
data:
  TESSERAL_INTERNAL_API_CONSOLE_PROJECT_ID: "project_3xl34fv7r4snik1ekj2zvouyp"
  TESSERAL_INTERNAL_API_SESSION_SIGNING_KEYS_KMS_BACKEND: "aws_kms_v1"
  TESSERAL_INTERNAL_API_SESSION_SIGNING_KEYS_KMS_AWS_KMS_V1_KEY_ID: "b312eb62-dc0b-44dc-8917-9801f0142953"

  # TODO
  TESSERAL_INTERNAL_API_GOOGLE_OAUTH_CLIENT_SECRETS_KMS_BACKEND: "dangerously_store_plaintext_private_keys"
  TESSERAL_INTERNAL_API_MICROSOFT_OAUTH_CLIENT_SECRETS_KMS_BACKEND: "dangerously_store_plaintext_private_keys"
  TESSERAL_INTERNAL_API_GITHUB_OAUTH_CLIENT_SECRETS_KMS_BACKEND: "dangerously_store_plaintext_private_keys"
  TESSERAL_INTERNAL_API_AUTHENTICATOR_APP_SECRETS_KMS_BACKEND: "dangerously_store_plaintext_private_keys"
  TESSERAL_INTERNAL_API_OIDC_CLIENT_SECRETS_KMS_BACKEND: "dangerously_store_plaintext_private_keys"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tesseral
  name: tesseral-internal-api
  labels:
    app: tesseral-internal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseral-internal-api
  template:
    metadata:
      labels:
        app: tesseral-internal-api
    spec:
      containers:
        - name: tesseral-internal-api
          image: ghcr.io/tesseral-labs/unstable-tesseral-internal-api:sha-52b9d08
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tesseral-internal-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: tesseral
  name: tesseral-internal-api
spec:
  selector:
    app: tesseral-internal-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tesseral
  name: tesseral-backend-api
data:
  TESSERAL_BACKEND_API_TESSERAL_INTERNAL_API_ENDPOINT: "http://tesseral-internal-api.tesseral.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tesseral
  name: tesseral-backend-api
  labels:
    app: tesseral-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseral-backend-api
  template:
    metadata:
      labels:
        app: tesseral-backend-api
    spec:
      containers:
        - name: tesseral-backend-api
          image: ghcr.io/tesseral-labs/unstable-tesseral-backend-api:sha-52b9d08
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tesseral-backend-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: tesseral
  name: tesseral-backend-api
spec:
  selector:
    app: tesseral-backend-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tesseral
  name: tesseral-backend-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:337607240212:certificate/04124df7-c11a-4aa2-a438-253420076cf4
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesseral-backend-api
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tesseral
  name: tesseral-config-api
data:
  TESSERAL_CONFIG_API_TESSERAL_INTERNAL_API_ENDPOINT: "http://tesseral-internal-api.tesseral.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tesseral
  name: tesseral-config-api
  labels:
    app: tesseral-config-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseral-config-api
  template:
    metadata:
      labels:
        app: tesseral-config-api
    spec:
      containers:
        - name: tesseral-config-api
          image: ghcr.io/tesseral-labs/unstable-tesseral-config-api:sha-52b9d08
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tesseral-config-api
---
apiVersion: v1
kind: Service
metadata:
  namespace: tesseral
  name: tesseral-config-api
spec:
  selector:
    app: tesseral-config-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tesseral
  name: tesseral-config-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:337607240212:certificate/4dbf9972-2807-4bf8-98e5-0dffd9901fcf
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesseral-config-api
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tesseral
  name: tesseral-console
data:
  TESSERAL_CONSOLE_VAULT_ENDPOINT: "https://vault.console.laresset-selfhost1.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tesseral
  name: tesseral-console
  labels:
    app: tesseral-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseral-console
  template:
    metadata:
      labels:
        app: tesseral-console
    spec:
      containers:
        - name: tesseral-console
          image: ghcr.io/tesseral-labs/unstable-tesseral-console:sha-52b9d08
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tesseral-console
---
apiVersion: v1
kind: Service
metadata:
  namespace: tesseral
  name: tesseral-console
spec:
  selector:
    app: tesseral-console
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tesseral
  name: tesseral-console
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:337607240212:certificate/9cbf59f5-896f-4205-b596-edcfb4aa2424
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesseral-console
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tesseral
  name: tesseral-vault
data:
  TESSERAL_VAULT_TESSERAL_INTERNAL_API_ENDPOINT: "http://tesseral-internal-api.tesseral.svc.cluster.local"
  TESSERAL_VAULT_TRUSTED_HOST_HEADER: "Host"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tesseral
  name: tesseral-vault
  labels:
    app: tesseral-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseral-vault
  template:
    metadata:
      labels:
        app: tesseral-vault
    spec:
      containers:
        - name: tesseral-vault
          image: ghcr.io/tesseral-labs/unstable-tesseral-vault:sha-9bd39bd
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tesseral-vault
---
apiVersion: v1
kind: Service
metadata:
  namespace: tesseral
  name: tesseral-vault
spec:
  selector:
    app: tesseral-vault
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tesseral
  name: tesseral-vault
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:337607240212:certificate/fe424c8a-6c5a-454e-87d9-d3cc15fcf971
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesseral-vault
                port:
                  number: 80
