version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: "github.com/openauth/openauth/internal/gen"
plugins:
  - remote: buf.build/community/google-gnostic-openapi
    out: internal/gen/openapi-intermediate
    opt: paths=source_relative
inputs:
  - directory: internal/proto
    paths:
      - internal/proto/intermediate
      - internal/proto/openauth
