// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-wellknown.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getProjectTrustedDomains = `-- name: GetProjectTrustedDomains :many
SELECT
    id, project_id, domain
FROM
    project_trusted_domains
WHERE
    project_id = $1
`

func (q *Queries) GetProjectTrustedDomains(ctx context.Context, projectID uuid.UUID) ([]ProjectTrustedDomain, error) {
	rows, err := q.db.Query(ctx, getProjectTrustedDomains, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectTrustedDomain
	for rows.Next() {
		var i ProjectTrustedDomain
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
