// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-scim.sql

package queries

import (
	"context"
)

const one = `-- name: One :one
SELECT
    1
`

func (q *Queries) One(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, one)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
