// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries-backgroundworker.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getProjectWebhookSettings = `-- name: GetProjectWebhookSettings :one
SELECT
    id, project_id, app_id, create_time, update_time, direct_webhook_url
FROM
    project_webhook_settings
WHERE
    project_id = $1
`

func (q *Queries) GetProjectWebhookSettings(ctx context.Context, projectID uuid.UUID) (ProjectWebhookSetting, error) {
	row := q.db.QueryRow(ctx, getProjectWebhookSettings, projectID)
	var i ProjectWebhookSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AppID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DirectWebhookUrl,
	)
	return i, err
}
