// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-common.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getProjectIDByCustomAuthDomain = `-- name: GetProjectIDByCustomAuthDomain :one
SELECT
    id
FROM
    projects
WHERE
    custom_auth_domain = $1
    OR auth_domain = $1
`

func (q *Queries) GetProjectIDByCustomAuthDomain(ctx context.Context, customAuthDomain *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectIDByCustomAuthDomain, customAuthDomain)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
