// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries-saml.sql

package queries

import (
	"context"
)

const foo = `-- name: Foo :one
SELECT
    1
`

func (q *Queries) Foo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, foo)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
