// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/google/uuid"
)

type Organization struct {
	ID                                uuid.UUID
	ProjectID                         uuid.UUID
	DisplayName                       string
	OverrideLogInWithPasswordEnabled  *bool
	OverrideLogInWithGoogleEnabled    *bool
	OverrideLogInWithMicrosoftEnabled *bool
	GoogleHostedDomain                *string
	MicrosoftTenantID                 *string
}

type Project struct {
	ID                         uuid.UUID
	OrganizationID             *uuid.UUID
	LogInWithPasswordEnabled   bool
	LogInWithGoogleEnabled     bool
	LogInWithMicrosoftEnabled  bool
	GoogleOauthClientID        *string
	GoogleOauthClientSecret    *string
	MicrosoftOauthClientID     *string
	MicrosoftOauthClientSecret *string
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UnverifiedEmail *string
	VerifiedEmail   *string
	PasswordBcrypt  *string
	GoogleUserID    *string
	MicrosoftUserID *string
}
