#!/bin/sh

set -e

# rewrite TESSERAL_VAULT_TRUSTED_HOST_HEADER from "X-Forwarded-Host" to "$http_x_forwarded_host"
export TESSERAL_VAULT_TRUSTED_HOST_HEADER="http_$(echo "${TESSERAL_VAULT_TRUSTED_HOST_HEADER}" | tr '[:upper:]' '[:lower:]' | tr '-' '_')"

envsubst '${TESSERAL_VAULT_TESSERAL_INTERNAL_API_ENDPOINT},${TESSERAL_VAULT_TRUSTED_HOST_HEADER}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
