name: generated-lint
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  proto:
    name: make proto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: make proto
        run: |
          npm install
          make proto
      - name: check if index is dirty
        run: git diff-index --quiet HEAD
