name: golang-test
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  gotest:
    name: go test
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: go test
        run: |
          go test -v ./...
  workflow-telemetry-action:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: 'false'
