name: golang-test
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  gotest:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: go test
        run: |
          go test -v ./...
