name: staticcheck-lint
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  staticcheck:
    name: lint
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
