name: vaultui-ci
on:
  push:
permissions:
  contents: read
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: |
          yarn workspace @tesseral/vault-ui run ci
          yarn workspace @tesseral/vault-ui run fmt-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: |
          yarn workspace @tesseral/vault-ui run ci
          yarn workspace @tesseral/vault-ui run lint
  tsc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: |
          yarn workpsace @tesseral/vault-ui run ci
          yarn workspace @tesseral/vault-ui run tsc-check
